all:
	cat static/yadmin/plugins/jQuery/jquery-2.2.3.min.js > static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/jquery-ui.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	echo "$$.widget.bridge('uibutton', $$.ui.button);" >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/bootstrap/js/bootstrap.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/raphael-min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/morris/morris.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/sparkline/jquery.sparkline.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/knob/jquery.knob.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/moment.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/daterangepicker/daterangepicker.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/datepicker/bootstrap-datepicker.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/slimScroll/jquery.slimscroll.min.js >> static/yadmin/dist/js/vendor.js
	echo ';' >> static/yadmin/dist/js/vendor.js
	cat static/yadmin/plugins/fastclick/fastclick.js >> static/yadmin/dist/js/vendor.js
	webpack
