from django.utils.translation import ugettext_lazy as _


CURRENCY_CHOICES = (
    ('AED', _('United Arab Emirates Dirham')),
    ('AFN', _('Afghanistan Afghani')),
    ('ALL', _('Albania Lek')),
    ('AMD', _('Armenia Dram')),
    ('ANG', _('Netherlands Antilles Guilder')),
    ('AOA', _('Angola Kwanza')),
    ('ARS', _('Argentina Peso')),
    ('AUD', _('Australia Dollar')),
    ('AWG', _('Aruba Guilder')),
    ('AZN', _('Azerbaijan New Manat')),
    ('BAM', _('Bosnia and Herzegovina Convertible Marka')),
    ('BBD', _('Barbados Dollar')),
    ('BDT', _('Bangladesh Taka')),
    ('BGN', _('Bulgaria Lev')),
    ('BHD', _('Bahrain Dinar')),
    ('BIF', _('Burundi Franc')),
    ('BMD', _('Bermuda Dollar')),
    ('BND', _('Brunei Darussalam Dollar')),
    ('BOB', _('Bolivia Bolíviano')),
    ('BRL', _('Brazil Real')),
    ('BSD', _('Bahamas Dollar')),
    ('BTN', _('Bhutan Ngultrum')),
    ('BWP', _('Botswana Pula')),
    ('BYN', _('Belarus Ruble')),
    ('BZD', _('Belize Dollar')),
    ('CAD', _('Canada Dollar')),
    ('CDF', _('Congo/Kinshasa Franc')),
    ('CHF', _('Switzerland Franc')),
    ('CLP', _('Chile Peso')),
    ('CNY', _('China Yuan Renminbi')),
    ('COP', _('Colombia Peso')),
    ('CRC', _('Costa Rica Colon')),
    ('CUC', _('Cuba Convertible Peso')),
    ('CUP', _('Cuba Peso')),
    ('CVE', _('Cape Verde Escudo')),
    ('CZK', _('Czech Republic Koruna')),
    ('DJF', _('Djibouti Franc')),
    ('DKK', _('Denmark Krone')),
    ('DOP', _('Dominican Republic Peso')),
    ('DZD', _('Algeria Dinar')),
    ('EGP', _('Egypt Pound')),
    ('ERN', _('Eritrea Nakfa')),
    ('ETB', _('Ethiopia Birr')),
    ('EUR', _('Euro Member Countries')),
    ('FJD', _('Fiji Dollar')),
    ('FKP', _('Falkland Islands (Malvinas) Pound')),
    ('GBP', _('United Kingdom Pound')),
    ('GEL', _('Georgia Lari')),
    ('GGP', _('Guernsey Pound')),
    ('GHS', _('Ghana Cedi')),
    ('GIP', _('Gibraltar Pound')),
    ('GMD', _('Gambia Dalasi')),
    ('GNF', _('Guinea Franc')),
    ('GTQ', _('Guatemala Quetzal')),
    ('GYD', _('Guyana Dollar')),
    ('HKD', _('Hong Kong Dollar')),
    ('HNL', _('Honduras Lempira')),
    ('HRK', _('Croatia Kuna')),
    ('HTG', _('Haiti Gourde')),
    ('HUF', _('Hungary Forint')),
    ('IDR', _('Indonesia Rupiah')),
    ('ILS', _('Israel Shekel')),
    ('IMP', _('Isle of Man Pound')),
    ('INR', _('India Rupee')),
    ('IQD', _('Iraq Dinar')),
    ('IRR', _('Iran Rial')),
    ('ISK', _('Iceland Krona')),
    ('JEP', _('Jersey Pound')),
    ('JMD', _('Jamaica Dollar')),
    ('JOD', _('Jordan Dinar')),
    ('JPY', _('Japan Yen')),
    ('KES', _('Kenya Shilling')),
    ('KGS', _('Kyrgyzstan Som')),
    ('KHR', _('Cambodia Riel')),
    ('KMF', _('Comoros Franc')),
    ('KPW', _('Korea (North) Won')),
    ('KRW', _('Korea (South) Won')),
    ('KWD', _('Kuwait Dinar')),
    ('KYD', _('Cayman Islands Dollar')),
    ('KZT', _('Kazakhstan Tenge')),
    ('LAK', _('Laos Kip')),
    ('LBP', _('Lebanon Pound')),
    ('LKR', _('Sri Lanka Rupee')),
    ('LRD', _('Liberia Dollar')),
    ('LSL', _('Lesotho Loti')),
    ('LYD', _('Libya Dinar')),
    ('MAD', _('Morocco Dirham')),
    ('MDL', _('Moldova Leu')),
    ('MGA', _('Madagascar Ariary')),
    ('MKD', _('Macedonia Denar')),
    ('MMK', _('Myanmar (Burma) Kyat')),
    ('MNT', _('Mongolia Tughrik')),
    ('MOP', _('Macau Pataca')),
    ('MRO', _('Mauritania Ouguiya')),
    ('MUR', _('Mauritius Rupee')),
    ('MVR', _('Maldives (Maldive Islands) Rufiyaa')),
    ('MWK', _('Malawi Kwacha')),
    ('MXN', _('Mexico Peso')),
    ('MYR', _('Malaysia Ringgit')),
    ('MZN', _('Mozambique Metical')),
    ('NAD', _('Namibia Dollar')),
    ('NGN', _('Nigeria Naira')),
    ('NIO', _('Nicaragua Cordoba')),
    ('NOK', _('Norway Krone')),
    ('NPR', _('Nepal Rupee')),
    ('NZD', _('New Zealand Dollar')),
    ('OMR', _('Oman Rial')),
    ('PAB', _('Panama Balboa')),
    ('PEN', _('Peru Sol')),
    ('PGK', _('Papua New Guinea Kina')),
    ('PHP', _('Philippines Peso')),
    ('PKR', _('Pakistan Rupee')),
    ('PLN', _('Poland Zloty')),
    ('PYG', _('Paraguay Guarani')),
    ('QAR', _('Qatar Riyal')),
    ('RON', _('Romania New Leu')),
    ('RSD', _('Serbia Dinar')),
    ('RUB', _('Russia Ruble')),
    ('RWF', _('Rwanda Franc')),
    ('SAR', _('Saudi Arabia Riyal')),
    ('SBD', _('Solomon Islands Dollar')),
    ('SCR', _('Seychelles Rupee')),
    ('SDG', _('Sudan Pound')),
    ('SEK', _('Sweden Krona')),
    ('SGD', _('Singapore Dollar')),
    ('SHP', _('Saint Helena Pound')),
    ('SLL', _('Sierra Leone Leone')),
    ('SOS', _('Somalia Shilling')),
    ('SPL*', _('Seborga Luigino')),
    ('SRD', _('Suriname Dollar')),
    ('STD', _('São Tomé and Príncipe Dobra')),
    ('SVC', _('El Salvador Colon')),
    ('SYP', _('Syria Pound')),
    ('SZL', _('Swaziland Lilangeni')),
    ('THB', _('Thailand Baht')),
    ('TJS', _('Tajikistan Somoni')),
    ('TMT', _('Turkmenistan Manat')),
    ('TND', _('Tunisia Dinar')),
    ('TOP', _("Tonga Pa'anga")),
    ('TRY', _('Turkey Lira')),
    ('TTD', _('Trinidad and Tobago Dollar')),
    ('TVD', _('Tuvalu Dollar')),
    ('TWD', _('Taiwan New Dollar')),
    ('TZS', _('Tanzania Shilling')),
    ('UAH', _('Ukraine Hryvnia')),
    ('UGX', _('Uganda Shilling')),
    ('USD', _('United States Dollar')),
    ('UYU', _('Uruguay Peso')),
    ('UZS', _('Uzbekistan Som')),
    ('VEF', _('Venezuela Bolivar')),
    ('VND', _('Viet Nam Dong')),
    ('VUV', _('Vanuatu Vatu')),
    ('WST', _('Samoa Tala')),
    ('XAF', _('Communauté Financière Africaine (BEAC) CFA Franc BEAC')),
    ('XCD', _('East Caribbean Dollar')),
    ('XDR', _('International Monetary Fund (IMF) Special Drawing Rights')),
    ('XOF', _('Communauté Financière Africaine (BCEAO) Franc')),
    ('XPF', _('Comptoirs Français du Pacifique (CFP) Franc')),
    ('YER', _('Yemen Rial')),
    ('ZAR', _('South Africa Rand')),
    ('ZMW', _('Zambia Kwacha')),
    ('ZWD', _('Zimbabwe Dollar')),
)
